### ISSUE TITLE
大佬参加了华为云的青年班黑客松大赛了吗

### ISSUE THREAD

**Issue by hqchqc** [yananren2137/huawei-ai-food-challenge#1]
这次的赛题和你这个好像是一样的，可以参加一波，不过今天下午两点截止了，后悔没有早点看到，嘻嘻 否则我就白嫖了

**Comment by yananren2137** [comment]
那个比赛我也看到了，不过因为不是青年班的就没有奖励，所以就没参加发自我的华为手机-------- 原始邮件 --------发件人： beanBag <notifications@github.com>日期： 2020年5月8日周五 13:13收件人： yananren2137/huawei-ai-food-challenge <huawei-ai-food-challenge@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yananren2137/huawei-ai-food-challenge] 大佬参加了华为云的青年班黑客松大赛了吗 (#1)

这次的赛题和你这个好像是一样的，可以参加一波，不过今天下午两点截止了，后悔没有早点看到，嘻嘻 否则我就白嫖了

**Comment by hqchqc** [comment]
参加的话就第一了 参数调了好多天到0.978上不去了 想问问你是放在华为云的平台上训练的模型吗 还是本地 大概要跑多久呢 学习一下🤭

**Comment by yananren2137** [comment]
没有在华为云上，太贵了o(╥﹏╥)o
用TeslaV100，跑完三个阶段的训练，估计要30多个小时

**Comment by hqchqc** [comment]
牛牛牛 ( ఠൠఠ )ﾉ
